// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorApp2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BlazorApp2.Models
{
    public partial interface IEmployeeDBContextProcedures
    {
        Task<List<AllEmployeeResult>> AllEmployeeAsync(int? value, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DelectEmployee1Async(int? Id, int? value1, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertEmployeeAsync(string Name, string Email, string Phone, string Gender, string Skill, string Address, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SelectById1Result>> SelectById1Async(int? value, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEmployeeAsync(int? Id, string Name, string Email, string Phone, string Address, string Skill, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
